### ISSUE TITLE
insserv: warning: current stop runlevel(s) (empty) of script `asterisk' overrides LSB defaults (0 1 6).

### ISSUE THREAD

**Issue by wdoekes** [ossobv/asterisk-deb#2]
insserv: warning: current stop runlevel(s) (empty) of script `asterisk' overrides LSB defaults (0 1 6).

Fix:

```
# Default-Stop: (blank)
```

**Comment by wdoekes** [comment]
Cannot reproduce.

**Comment by DXXS** [comment]
Happens to me too :
$ update-rc.d asterisk disable
insserv: warning: current start runlevel(s) (empty) of script `asterisk' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `asterisk' overrides LSB defaults (0 1 6).

**Comment by wdoekes** [comment]
```
# dpkg -l asterisk | awk '/^ii/{print $3}'
1:16.26.0-0osso1+ubu20.04
```
```
# update-rc.d asterisk disable
```
```
# update-rc.d asterisk enable
```

Nope. Cannot reproduce.

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by DXXS** [comment]
$ asterisk -V
Asterisk 19.4.1
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by wdoekes** [comment]
That asterisk version does not look like it was built here. So you're in the wrong place :)

**Comment by DXXS** [comment]
I found this bug report when searching for the error message I encountered after building asterisk from the latest source.

**Comment by wdoekes** [comment]
Well. The runlevels in the asterisk init script should already exist:

https://github.com/asterisk/asterisk/blob/19/contrib/init.d/rc.debian.asterisk#L29-L39
https://github.com/asterisk/asterisk/blob/05a0b08222240dfc7828330767ac40c7156d606d/contrib/init.d/rc.debian.asterisk#L29-L39

If this doesn't work, you should see the bugs at https://issues.asterisk.org/
